apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2021-06-27T05:34:29Z"
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:rbac.authorization.kubernetes.io/autoupdate: {}
      f:rules: {}
    manager: openshift-apiserver
    operation: Update
    time: "2021-06-27T05:34:29Z"
  name: system:openshift:controller:cluster-quota-reconciliation-controller
  resourceVersion: "10864"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/system%3Aopenshift%3Acontroller%3Acluster-quota-reconciliation-controller
  uid: 9110d700-0a9a-421e-adee-74d153bc67ea
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  - quota.openshift.io
  resources:
  - clusterresourcequotas/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
