apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: viewcrq
rules:
- apiGroups:
  - ""
  - quota.openshift.io
  resources:
  - clusterresourcequotas
  verbs:
  - list
  - get
